services:
  db:
    image: pgvector/pgvector:pg17
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    ports:
      - "5432:5432" # postgres
      
    volumes: # for data persistence
      - postgres_data:/var/lib/postgresql/data
    
    # auto-restart on crash
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5

  db-setup:
    build: .
    profiles: 
      - setup
    depends_on:
      db:
        condition: service_healthy
    command: setup.sh

volumes:
  postgres_data:
