services:
  db:
    # image: pgvector/pgvector:pg17
    image: timescale/timescaledb-ha:pg17
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    env_file:
      - .env

    ports:
      - "5432:5432" # postgres
      
    volumes: # for data persistence
      - postgres_data:/var/lib/postgresql/data
    
    # auto-restart on crash
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    profiles:
      - setup
    depends_on:
      db:
        condition: service_healthy
    env_file:
        - .env

  index:
    build:
      context: .
      dockerfile: Dockerfile.setup
    profiles:
      - setup
    depends_on:
      db-setup:
        condition: service_completed_successfully
    env_file:
        - .env
    command: python src/graphics_db_server/scripts/ingest_data.py

  api:
    build:
      context: .
      dockerfile: Dockerfile.setup
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: uvicorn src.graphics_db_server.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
